# Generated by Django 3.1.7 on 2021-03-20 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='dz',
            name='paperid',
        ),
        migrations.DeleteModel(
            name='Dz_authorid',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='author',
        ),
        migrations.RemoveField(
            model_name='techs',
            name='studid',
        ),
        migrations.RemoveField(
            model_name='techs',
            name='teacid',
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pubdate',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pubdate',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='news',
            table='jn_news',
        ),
        migrations.AlterModelTable(
            name='notice',
            table='jn_notice',
        ),
        migrations.DeleteModel(
            name='Dz',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Techs',
        ),
    ]
