# Generated by Django 3.1.7 on 2021-03-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210320_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pubdate', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('content', models.TextField(blank=True, max_length=50000, null=True)),
                ('status', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('thumbupcount', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jn_paper',
            },
        ),
    ]
