# Generated by Django 3.1.7 on 2021-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(default=None, max_length=50000, null=True)),
            ],
            options={
                'db_table': 'jn_config',
            },
        ),
    ]
