# Generated by Django 3.1.7 on 2021-03-20 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaperThumbUp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thumbups', models.TextField(default=',')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cimp_userpaperthumbup',
            },
        ),
    ]
