# Generated by Django 3.1.7 on 2021-03-20 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userpaperthumbup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacherRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myteachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystudents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
